---
title: "STAT 4279/5279: Statistical Computing"
output:
  html_document:
    toc: false
    theme: cosmo
---

Welcome! This page contains links to lecture slides for **STAT 4279/5279**.

All slides are provided as HTML and are best viewed in a modern web browser.


### Module 01: R Fundamentals
- **Data Types and Operators**
  - [Slides](1-Fundamentals/R_Basics.html)
  - [Source](1-Fundamentals/R_Basics.Rmd)
  - [Code](1-Fundamentals/code_R_Basics.R)
  
- **Vectors and Matrices**
  - [Slides](1-Fundamentals/Vectors_Matrices.html)
  - [Source](1-Fundamentals/Vectors_Matrices.Rmd)
  - [Code](1-Fundamentals/code_Vectors_Matrices.R)
  
- **Lists and Data frames**
  - [Slides](1-Fundamentals/Lists_Dataframes.html)
  - [Source](1-Fundamentals/Lists_Dataframes.Rmd)
  - [Code](1-Fundamentals/code_Lists_Dataframes.R)

- **Factors**
  - [Slides](1-Fundamentals/Factors.html)
  - [Source](1-Fundamentals/Factors.Rmd)
  - [Code1](1-Fundamentals/code_Factors.R) and [Code2](1-Fundamentals/code_more_Factors.R)
  - [Notes](1-Fundamentals/Factor_encoding.pdf)

### Module 02: Control Flow and Functions

- **Conditionals and Iteration**
  - [Slides](2-ControlFlow/controlflow.html)
  - [Source](2-ControlFlow/controlflow.Rmd)
  - [Code](2-ControlFlow/code_controlflow.R) 

- **apply() family**
  - [Slides](2-ControlFlow/apply.html)
  - [Source](2-ControlFlow/apply.Rmd)
  - [Code](2-ControlFlow/code_apply.R) 

- **Writing Functions**
  - [Slides](2-ControlFlow/functions.html)
  - [Source](2-ControlFlow/functions.Rmd)
  - [Code](2-ControlFlow/code_functions.R) 

### Module 03: Sampling and Simulations 

- **Sampling**
  - [Slides](3-Sampling and Simulations/Sampling.html)
  - [Source](3-Sampling and Simulations/Sampling.Rmd)
  - [Code](3-Sampling and Simulations/code_sampling.R) 

- **Inverse Transform Sampling**
  - [Slides](3-Sampling and Simulations/inverseCDF.html)
  - [Source](3-Sampling and Simulations/inverseCDF.Rmd)
  - [Code](3-Sampling and Simulations/code_inverseCDF.R) 

- **Rejection and Importance Sampling**
  - [Slides](3-Sampling and Simulations/MoreSampling.html)
  - [Source](3-Sampling and Simulations/MoreSampling.Rmd)
  - [Code1](3-Sampling and Simulations/code_moresampling.R) 
  - [Code2](3-Sampling and Simulations/code_SIR.R) 


- **Simulations for the Null Distribution**
  - [Slides](3-Sampling and Simulations/Resampling_intro.html)
  - [Source](3-Sampling and Simulations/Resampling_intro.Rmd)
  - [Code](3-Sampling and Simulations/code_resampling_intro.R) 
  
- **More Permutation and Bootstrap**
  - [Slides](3-Sampling and Simulations/More_Resampling.html)
  - [Source](3-Sampling and Simulations/More_Resampling.Rmd)

- **Jackknife and Bias Estimation**
  - [Slides](3-Sampling and Simulations/jackknife.html)
  - [Source](3-Sampling and Simulations/jackknife.Rmd)
  
- **Structured Permutation and Bootstrap**
  - [Slides](3-Sampling and Simulations/Structured_Resampling.html)
  - [Source](3-Sampling and Simulations/Structured_Resampling.Rmd)

### Module 04: Statistical Learning

- **Introduction to Statistical Learning**
  - [Slides](4-Statistical Learning/statistical_learning_intro.html)
  - [Source](4-Statistical Learning/statistical_learning_intro.Rmd)
  
- **Tuning via Cross-validation**
  - [Slides](4-Statistical Learning/tuning_cross_validation.html)
  - [Source](4-Statistical Learning/tuning_cross_validation.Rmd)
  - [Code](4-Statistical Learning/code_tuning_cv.R)

- **Regularized Regression**
  - [Slides](4-Statistical Learning/regularized_regression.html)
  - [Source](4-Statistical Learning/regularized_regression.Rmd)
  - [Code1](4-Statistical Learning/helper_functions_regression.R)
  - [Code2](4-Statistical Learning/implementation_regression.R)
  - [Notes](4-Statistical Learning/04_16_26.pdf)

- **Classification**
  - [Slides](4-Statistical Learning/classification.html)
  - [Source](4-Statistical Learning/classification.Rmd)
  - [Code](4-Statistical Learning/code_logistic_regression.R)

### Module 05: Tidyverse

- **Introduction to Tidyverse**
  - [Slides](5-Tidyverse/tidyverse_intro.html)
  - [Source](5-Tidyverse/tidyverse_intro.Rmd)
  
- **Tidyverse Part II**
  - [Slides](5-Tidyverse/tidyverse_part2.html)
  - [Source](5-Tidyverse/tidyverse_part2.Rmd)
  
  
### Notes

- Slides may be updated periodically.
- Please refresh your browser if something looks out of date.
- For questions, post on Ed Discussion or reach out to me directly.
